# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
description: >- # this means to ignore newlines until "baseurl:"
  An introduction to advanced paradigms of modelling and solving Reinforcement Learning problems.
  Topics include modern model-free on- and offline RL algorithms,
  meta-learning paradigms and learning RL components for transfer learning, continual learning or mult-agent problems.
  Student learn to develop research ideas through experimentation as well as an exchange of ideas in a seminar-style format.
baseurl: "/csci000" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#number: CSCI 000
title: Advanced Topics in Deep Reinforcement Learning
semester: Summer 2024

navigation:
  - title: Overview
    subfolderitems:
      - page: Description
        url: '#description'
      - page: Learning Goals
        url: '#goals'
      - page: Resources
        url: '#resources'
  - title: Coursework
    subfolderitems:
      - page: Quizzes
        url: '#quizzes'
      - page: Seminar
        url: '#seminar'
      - page: Exam
        url: '#exam'
  - page: Commitments
    url: '#commitments'

instructors:
  - id: theeimer
    name: Theresa Eimer
    email: t.eimer@ai.uni-hannover.de
    web: http://ozark.hendrix.edu/~yorgey
    phone: (501) 450-1377
    officehours: https://byorgey.youcanbook.me
  - id: adi
    name: Aditya Mohan
    email: a.mohan@ai.uni-hannover.de
    web: http://mark.goadrich.com
    phone: (501) 450-1367
    officehours: http://mark.goadrich.com/schedule.html

offerings:
  - name: Lecture
    loc: MCREY 110
    time: MWF 8:10am - 9:00am
    instructor: theeimer
  - name: Seminar
    loc: MCREY 110
    time: MWF 11:10am - 12:00pm
    instructor: aditys

resources:
  - name: Python 3.10
    image: assets/images/pythonlogo.png
    url: http://python.org
  - name: Azure Notebooks
    image: assets/images/azure.png
    url: https://notebooks.azure.com/
  - name: Pycharm
    image: assets/images/pycharmlogo.png
    url: https://www.jetbrains.com/pycharm/

extra-resources:
  - name: "How to Think Like a Computer Scientist: Interactive Edition"
    image: assets/images/runestone_logo.png
    url: https://runestone.academy/runestone/books/published/thinkcspy/index.html
  - name: Python Tutor
    image: assets/images/python_tutor.png
    url: http://pythontutor.com/
  - name: CodingBat Python
    image: assets/images/codingbat.jpg
    url: https://codingbat.com/python
  - name: CheckiO Python Practice
    image: assets/images/checkio_logo_small.png
    url: https://py.checkio.org/

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
